### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by ppigazzini** [Dark42ed/fishtest-gui#1]
Clean windows 10 vm, just after the double click

![Untitled](https://user-images.githubusercontent.com/15718418/136580116-94662af2-aa8d-4830-a807-05c033775348.jpg)

**Comment by Dark42ed** [comment]
Thanks for testing! This seemed to be an issue if the GUI couldn't find an already existing msys2 installation. I should probably be testing on a clean windows vm now that I think about it. 
Fixed in 404c867827480a0e1662ce129e7d991effec81b0.

**Comment by ppigazzini** [comment]
You **must** test on a clean Windows VM :D
