### ISSUE TITLE
Installation folder doesn't follow the msys2 suggestion

### ISSUE THREAD

**Issue by ppigazzini** [Dark42ed/fishtest-gui#2]
[msys2](https://www.msys2.org/) suggests:
> Enter your desired Installation Folder (short ASCII-only path on a NTFS volume, no accents, no spaces, no symlinks, no subst or network drives, no FAT).

This path is long and uses the Windows username (possibility of spaces, accents etc.)
https://github.com/Dark42ed/fishtest-gui/blob/1093c7817b0b5d13bb4d53d7122ec90e501e229e/main.py#L15-L18

IMO better to stick to the choco default (the Windows contributor has already that) updating also here:

https://github.com/Dark42ed/fishtest-gui/blob/1093c7817b0b5d13bb4d53d7122ec90e501e229e/main.py#L94-L103

BTW adding also the flag "-f" that function can be used to install and to update msys2.

**Comment by Dark42ed** [comment]
I will try to get a fix for this soon. Thanks!

**Comment by Dark42ed** [comment]
Should be fixed in the newest release (v1.1). I tested on a semi-clean vm (Tested then cleaned environment vars and any residues then tested again). If you could also test that would mean a lot!
