### ISSUE TITLE
Hide password

### ISSUE THREAD

**Issue by ppigazzini** [Dark42ed/fishtest-gui#3]
IMO better to hide the password, with a "Show" button that must be kept pressed.
An user could post a screenshot. Or clear the fields after pushing the "Start" button. After the first start `python3 worker.py` will load the data from `fishtest.cfg`.

![Untitled](https://user-images.githubusercontent.com/15718418/136712533-02614067-e038-40d8-bfb8-ef8c2e0df066.jpg)

**Comment by Dark42ed** [comment]
Good idea. I'll implement that when I can.
